kind: Ingress
metadata:
  name: application
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8055
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
