apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/likelion-cardinal/cardinal-architect.git
    targetRevision: main
    path: prod/manifest/app-node/application

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
