apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.5/manifests/install.yaml
namespace: argocd
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          cardinal.io/role: system
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          cardinal.io/role: system
