apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.5/manifests/install.yaml
namespace: argocd
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          cardinal.io/role: system
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          cardinal.io/role: system

  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: argocd-application-controller
      spec:
        template:
          spec:
            containers:
              - name: argocd-application-controller
                resources:
                  requests:
                    memory: 192Mi
                  limits:
                    memory: 512Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
      spec:
        template:
          spec:
            containers:
              - name: argocd-repo-server
                resources:
                  requests:
                    memory: 128Mi
                  limits:
                    memory: 448Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-server
      spec:
        template:
          spec:
            containers:
              - name: argocd-server
                resources:
                  requests:
                    memory: 96Mi
                  limits:
                    memory: 256Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-redis
      spec:
        template:
          spec:
            containers:
              - name: redis
                resources:
                  requests:
                    memory: 32Mi
                  limits:
                    memory: 128Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-applicationset-controller
      spec:
        template:
          spec:
            containers:
              - name: argocd-applicationset-controller
                resources:
                  requests:
                    memory: 48Mi
                  limits:
                    memory: 96Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-notifications-controller
      spec:
        template:
          spec:
            containers:
              - name: argocd-notifications-controller
                resources:
                  requests:
                    memory: 32Mi
                  limits:
                    memory: 64Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-dex-server
      spec:
        template:
          spec:
            containers:
              - name: dex
                resources:
                  requests:
                    memory: 24Mi
                  limits:
                    memory: 32Mi
