apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.15.1/deploy/static/provider/baremetal/deploy.yaml
  - daemonset.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx

  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
        namespace: ingress-nginx
      spec:
        type: NodePort
        externalTrafficPolicy: Cluster
        ports:
          - name: http
            port: 80
            nodePort: 30080
          - name: https
            port: 443
            nodePort: 30443

  - target:
      kind: Job
      namespace: ingress-nginx
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          cardinal.io/role: application
